# -*- coding: utf-8 -*-
"""last

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TaPTc-Dt84CGMVId8_K0yZp3ZG5XaVKH
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
data = pd.read_csv("")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
data = pd.read_csv("/content/study_vs_marks (1).csv")
X = data[['study_hours', 'sleep_hours']]
y = data['exam_score']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("\nModel Equation:")
print(f"exam_score = {model.coef_[0]:.2f} * study_hours + {model.coef_[1]:.2f} * sleep_hours + {model.intercept_:.2f}")
study = float(input("Enter study hours: "))
sleep = float(input("Enter sleep hours: "))
prediction = model.predict([[study, sleep]])
print("Predicted Exam Score:", prediction[0])
plt.scatter(X_test['study_hours'], y_test, color='blue', label='Actual')
plt.scatter(X_test['study_hours'], y_pred, color='red', label='Predicted')
plt.xlabel("Study Hours")
plt.ylabel("Exam Score")
plt.legend()
plt.title("Study Hours vs Exam Score")
plt.show()

# @title AI prompt cell

import ipywidgets as widgets
from IPython.display import display, HTML, Markdown,clear_output
from google.colab import ai

dropdown = widgets.Dropdown(
    options=[],
    layout={'width': 'auto'}
)

def update_model_list(new_options):
    dropdown.options = new_options
update_model_list(ai.list_models())

text_input = widgets.Textarea(
    placeholder='Ask me anything....',
    layout={'width': 'auto', 'height': '100px'},
)

button = widgets.Button(
    description='Submit Text',
    disabled=False,
    tooltip='Click to submit the text',
    icon='check'
)

output_area = widgets.Output(
     layout={'width': 'auto', 'max_height': '300px','overflow_y': 'scroll'}
)

def on_button_clicked(b):
    with output_area:
        output_area.clear_output(wait=False)
        accumulated_content = ""
        for new_chunk in ai.generate_text(prompt=text_input.value, model_name=dropdown.value, stream=True):
            if new_chunk is None:
                continue
            accumulated_content += new_chunk
            clear_output(wait=True)
            display(Markdown(accumulated_content))

button.on_click(on_button_clicked)
vbox = widgets.GridBox([dropdown, text_input, button, output_area])

display(HTML("""
<style>
.widget-dropdown select {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
.widget-textarea textarea {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
</style>
"""))
display(vbox)

import sys
{sys.executable}

"""Now, let's create a Streamlit application file. This code will write the Streamlit app to a file named `app.py`."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# from sklearn.linear_model import LinearRegression
# 
# # Load the pre-trained model and data (assuming it's available or re-train)
# # In a real-world scenario, you would typically save and load your model (e.g., using joblib or pickle).
# # For simplicity, we'll re-train a basic model here, or you can load an existing one.
# 
# # Assuming `X_train`, `y_train` from your notebook are accessible or can be re-created.
# # For this example, let's create dummy data for demonstration purposes if the kernel state isn't directly transferable.
# # In a full deployment, you'd load the actual model.
# 
# # Re-create a simplified model for the Streamlit app if the global variables are not directly accessible.
# # In Colab, the kernel state is shared, but for a standalone Streamlit app, we'd need to re-initialize or load.
# 
# # To make this self-contained, we'll retrain the model with some dummy data if not explicitly loaded.
# # However, since the prompt says 'add streamlit code to my model', we should try to use the existing trained model.
# # Let's assume the model and its coefficients are known from the previous execution.
# 
# # From your previous execution:
# # model.coef_[0] = 4.82 (study_hours)
# # model.coef_[1] = 2.01 (sleep_hours)
# # model.intercept_ = 1.47
# 
# # A simple way to represent the model's coefficients in Streamlit without loading a full model object:
# class SimpleLinearRegression:
#     def __init__(self, coef, intercept):
#         self.coef_ = coef
#         self.intercept_ = intercept
# 
#     def predict(self, X):
#         X = np.array(X)
#         return X @ self.coef_ + self.intercept_
# 
# # Using the coefficients from your executed cell 9VPO95tRch4o
# model = SimpleLinearRegression(coef_=np.array([4.82, 2.01]), intercept_=1.47)
# 
# st.title('Exam Score Prediction App')
# st.write('Enter the study and sleep hours to predict the exam score.')
# 
# # Input widgets
# study_hours = st.slider('Study Hours', min_value=0.0, max_value=10.0, value=5.0, step=0.1)
# sleep_hours = st.slider('Sleep Hours', min_value=0.0, max_value=10.0, value=7.0, step=0.1)
# 
# # Make prediction
# if st.button('Predict Exam Score'):
#     # Prepare input for prediction
#     input_data = pd.DataFrame([[study_hours, sleep_hours]], columns=['study_hours', 'sleep_hours'])
#     prediction = model.predict(input_data)
# 
#     st.success(f'Predicted Exam Score: {prediction[0]:.2f}')
#

"""To run this Streamlit application, you will need to open a new terminal in Colab (Go to `File` > `New notebook` and then navigate to `View` > `Terminal`).

Then, execute the following command in the terminal:

```bash
streamlit run app.py & npx localtunnel --port 8501
```

This command will launch the Streamlit app and provide a public URL to access it in your browser. Look for the `your url is:` message in the terminal output.

**Note:** If you close the terminal or stop the process, the Streamlit app will no longer be accessible.
"""
