# -*- coding: utf-8 -*-
"""python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOU9aAYcNq-mQmvWKALRUf1S6h6Imbuc
"""
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt
data = pd.read_csv("/content/study_vs_marks (1).csv")
X = data[['study_hours', 'sleep_hours']]
y = data['exam_score']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print("\nModel Equation:")
print(f"exam_score = {model.coef_[0]:.2f} * study_hours + {model.coef_[1]:.2f} * sleep_hours + {model.intercept_:.2f}")
study = float(input("Enter study hours: "))
sleep = float(input("Enter sleep hours: "))
prediction = model.predict([[study, sleep]])
print("Predicted Exam Score:", prediction[0])
plt.scatter(X_test['study_hours'], y_test, color='blue', label='Actual')
plt.scatter(X_test['study_hours'], y_pred, color='red', label='Predicted')
plt.xlabel("Study Hours")
plt.ylabel("Exam Score")
plt.legend()
plt.title("Study Hours vs Exam Score")
plt.show()

pip install streamlit

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

st.set_page_config(layout='wide')
st.title('Exam Score Predictor')

# Load data (assuming the CSV is accessible in the Colab environment)
data = pd.read_csv('/content/study_vs_marks (1).csv')

# Prepare data for model training
X = data[['study_hours', 'sleep_hours']]
y = data['exam_score']

# Train the Linear Regression Model
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)

st.header('Predict Your Exam Score')

# Get user input with sliders based on data ranges
study_hours = st.slider('Study Hours', min_value=float(X['study_hours'].min()), max_value=float(X['study_hours'].max()), value=5.0, step=0.1)
sleep_hours = st.slider('Sleep Hours', min_value=float(X['sleep_hours'].min()), max_value=float(X['sleep_hours'].max()), value=7.0, step=0.1)

# Make prediction
if st.button('Predict Score'):
    prediction = model.predict([[study_hours, sleep_hours]])[0]
    st.success(f'Predicted Exam Score: {prediction:.2f}')

st.subheader('Model Details')
st.write(f"Model Equation: exam_score = {model.coef_[0]:.2f} * study_hours + {model.coef_[1]:.2f} * sleep_hours + {model.intercept_:.2f}")

# Save the Streamlit app code to a file
with open('app.py', 'w') as f:
    f.write(st.file_contents)

import subprocess

# Run the Streamlit app in the background
# The ngrok part is needed to expose the local Streamlit server to the internet
# and get a publicly accessible URL in Google Colab.

# You might need to install ngrok first if you haven't already:
# !pip install pyngrok

# This command will launch Streamlit. Look for a public URL in the output
# after running this cell. It usually starts with 'https://xxxx-xx-xxx-xxx-xxx.ngrok-free.app'
print("Starting Streamlit app... This may take a moment. Look for the public URL above.")
process = subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

# This part is optional and tries to capture ngrok URL automatically
# For a more robust solution, you would typically run ngrok in a separate process
# and then extract the URL.
# For now, please manually check the output for the public URL.

# To stop the Streamlit app, you might need to interrupt the kernel or restart it.
